# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1535993242);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1535993362);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1536051613);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1535984917);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1535993602);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1536047893);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1535993722);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1535993482);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1535984224);
user_pref("browser.laterrun.bookkeeping.sessionCount", 5);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 62);
user_pref("browser.newtabpage.activity-stream.impressionId", "{d19e4b22-a694-46ee-825d-ff195074bb2a}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1536012000);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 2);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 0);
user_pref("browser.onboarding.notification.prompt-count", 3);
user_pref("browser.onboarding.notification.tour-ids-queue", "onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser");
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1536053246418");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1536055065418");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1536051472202");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1536055072202");
user_pref("browser.search.countryCode", "FR");
user_pref("browser.search.region", "FR");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20180406121424");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20180406121424");
user_pref("browser.startup.homepage_override.mstone", "59.0.2");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1535984236318");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "59.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 24);
user_pref("extensions.getAddons.cache.lastUpdate", 1535993246);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20180406121424");
user_pref("extensions.lastAppVersion", "59.0.2");
user_pref("extensions.lastPlatformVersion", "59.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shield-recipe-client.first_run", false);
user_pref("extensions.shield-recipe-client.user_id", "75c0e177-c6e5-4054-92ff-d762a52cb9b4");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"screenshots@mozilla.org\":\"7356d9c9-b5f2-4aaf-b3ea-a003219a4edb\"}");
user_pref("gecko.handlerService.migrated", true);
user_pref("idle.lastDailyNotification", 1535993714);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1535984266);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20180406121424");
user_pref("media.gmp-manager.lastCheck", 1535984266);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1535993714);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("services.blocklist.addons.checked", 1535992227);
user_pref("services.blocklist.clock_skew_seconds", 1135);
user_pref("services.blocklist.gfx.checked", 1535992227);
user_pref("services.blocklist.last_etag", "\"1535992146430\"");
user_pref("services.blocklist.last_update_seconds", 1535992227);
user_pref("services.blocklist.onecrl.checked", 1535992227);
user_pref("services.blocklist.pinning.checked", 1535992227);
user_pref("services.blocklist.plugins.checked", 1535992227);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1535993714);
user_pref("toolkit.startup.last_success", 1536044256);
user_pref("toolkit.telemetry.cachedClientID", "ff072e4d-5c74-49fa-837a-8e7d93b8b8c0");
user_pref("toolkit.telemetry.previousBuildID", "20180406121424");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
